# Generated by Django 5.0.6 on 2024-07-12 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job_portal', '0003_customuser_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='role',
        ),
    ]
