# Generated by Django 5.0.6 on 2024-07-14 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_portal', '0004_alter_jobfinderprofile_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='location',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AddField(
            model_name='job',
            name='salary',
            field=models.BigIntegerField(default=None, max_length=200),
        ),
    ]
